- name: move files
  hosts: all
  user: ubuntu
  tasks:
    - name: "copy files"
      become: yes
      copy: 
        src: ../../../../dist.tar.gz
        dest: /tmp/
    - name: Unarchive a file that is already on the remote machine
      unarchive:
        src: /tmp/dist.tar.gz
        dest: /tmp/
        remote_src: yes