version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...
commands:
  revert-migration:
    description: Revert the last migration if successfully run in the current workflow.
    steps:
      - run:
          name: "Revert migration"
          command: npm run migrations:revert
          when: on_fail

  destroy-environment:
    description: "destroy environment s3 bucket and delete cloudformation stack"
    parameters:
      bucket_name:
        type: string
        default: ""
      cf_stack:
        type: string
        default: "" 
    steps:
      - run:
          name: "Delete S3 Bucket"
          command: |
               aws s3api delete-bucket --bucket "<< parameters.bucket_name >>" --region "eu-central-1"
          when: on_fail
      - run:
          name: "Delete Cloudformation Stack"
          command: |
               aws cloudformation delete-stack --stack-name << parameters.cf_stack >>
          when: on_fail

  destroy-environment-linux:
    description: "destroy environment s3 bucket and delete cloudformation stack"
    parameters:
      bucket_name:
        type: string
        default: ""
      cf_stack:
        type: string
        default: "" 
    steps:
      - run:
          name: "install aws "
          command: |
                curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                unzip awscliv2.zip
                sudo ./aws/install
      - run:
          name: "Delete S3 Bucket"
          command: |
               aws s3api delete-bucket --bucket "<< parameters.bucket_name >>" --region "eu-central-1"
          when: on_fail
      - run:
          name: "Delete Cloudformation Stack"
          command: |
               aws cloudformation delete-stack --stack-name << parameters.cf_stack >>
          when: on_fail



jobs:
  build-frontend:
    docker:
      - image: node
    steps:
      - checkout   
      - run:
          name: "compile and build"
          command: |
             cd ~/project/frontend && npm i && npm run build
      - destroy-environment-linux:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
      - persist_to_workspace:
          root: ./
          paths:
             - ./frontend/node_modules  
             - ./frontend/dist
             
  build-backend:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: "create .env"
          command: |
              echo ENVIRONMENT=production > ~/project/backend/.env
              echo TYPEORM_DATABASE=postgres >> ~/project/backend/.env
              echo TYPEORM_CONNECTION=postgres >> ~/project/backend/.env
              echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ~/project/backend/.env
              echo TYPEORM_HOST=${TYPEORM_HOST} >> ~/project/backend/.env
              echo TYPEORM_PORT=${TYPEORM_PORT} >> ~/project/backend/.env
              echo TYPEORM_USERNAME=${TYPEORM_USERNAME} >> ~/project/backend/.env
              echo TYPEORM_PASSWORD=${TYPEORM_PASSWORD} >> ~/project/backend/.env
              echo TYPEORM_DATABASE=${TYPEORM_DATABASE} >> ~/project/backend/.env
      - run:
          name: "compile and build"
          command: |
             cd ~/project/backend && npm i && npm run build
      - destroy-environment-linux:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
      - persist_to_workspace:
          root: ./
          paths: 
             - ./backend/node_modules  
             - ./backend/dist

  test-frontend:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit test
          command: |
              cd ~/project/frontend && npm test
      - destroy-environment-linux:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"

  test-backend:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: Run unit test
          command: |
              cd ~/project/backend && npm run test         
      - destroy-environment-linux:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
  
  scan-frontend:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: scan front end vulnerabilities
          command: |
              cd ~/project/frontend && npm audit --audit-level=critical

  scan-backend:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: scan front end vulnerabilities
          command: |
              cd ~/project/backend && npm audit fix --audit-level=critical --force && npm audit --audit-level=critical

  configure-infrastructure:
    docker:
      - image: amazon/aws-cli
    steps: 
      - checkout
      - run:
          name: create stack for backend
          command: |
              aws cloudformation deploy --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" --template-file ~/project/.circleci/files/backend.yml --capabilities CAPABILITY_NAMED_IAM
      - run:
          name: save ips
          command: | 
              curl -H "Content-Type: text/plain" -H "token: 0cd52177-868d-4982-ac51-f1e6b661064a" --request PUT --data "$(aws ec2 describe-instances  --query 'Reservations[*].Instances[*].PublicIpAddress' --output=text)" https://api.memstash.io/values/ips        
      - run:
          name: create S3 bucket for frontend
          command: aws s3api create-bucket --bucket "frontend${CIRCLE_WORKFLOW_ID:0:7}" --region eu-central-1 --create-bucket-configuration LocationConstraint=eu-central-1
      - run:
          name: save s3 arn bucket
          command: |
              curl -H "Content-Type: text/plain" -H "token: 0cd52177-868d-4982-ac51-f1e6b661064a" --request PUT --data "arn:PARTITION:s3:::frontend${CIRCLE_WORKFLOW_ID:0:7}" https://api.memstash.io/values/s3bucket      
      - destroy-environment:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"           

  deploy-backend:
    docker:
      - image: python:3.7-alpine3.11
    steps: 
      - checkout 
      - add_ssh_keys:
           fingerprints: ["28:3e:56:65:72:cb:2f:83:41:5b:bd:d4:d5:21:17:e9"]
      - run:
          name: Install dependencies
          command: |
                apk add --update ansible
      - run: 
          name: disbale ssh checking
          command: |
                export ANSIBLE_HOST_KEY_CHECKING=False

      - run: 
          name: Configure server
          command: |
                apk --no-cache add curl && 
                echo [all] > ~/inventory.txt &&
                curl -H "token: 0cd52177-868d-4982-ac51-f1e6b661064a" --request GET https://api.memstash.io/values/ips >> ~/inventory.txt && 
                export ANSIBLE_HOST_KEY_CHECKING=False && ansible-playbook  -i ~/inventory.txt .circleci/ansible/roles/configure-server/playbook.yml --extra-vars "TYPEORM_HOST=${TYPEORM_HOST} TYPEORM_PORT=${TYPEORM_PORT} TYPEORM_USERNAME=${TYPEORM_USERNAME} TYPEORM_PASSWORD=${TYPEORM_PASSWORD} TYPEORM_DATABASE=${TYPEORM_DATABASE}"
      - destroy-environment-linux:
          bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
          cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"

  run-migrations:
      docker:
        - image: node
      steps:
        - checkout
        - attach_workspace:
            at: ./
        - run:
            name: migrate database
            command: cd ./backend/ && npm run migrations
        - destroy-environment-linux:
            bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
            cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"

  deploy-backend-andmovecode:
      docker:
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
           fingerprints: ["28:3e:56:65:72:cb:2f:83:41:5b:bd:d4:d5:21:17:e9"]
        - attach_workspace:
            at: ./
        - run:
            name: Install dependencies
            command: |
                apk add --update ansible
        - run:
            name: check list dist
            command: |
                ls -al ./
        - run:
            name: compress
            command: |
                tar -czvf ./dist.tar.gz ./backend/dist/
        - run:
            name: copy dist files ansible
            command: |
                apk --no-cache add curl &&
                echo [all] > ~/inventory.txt &&
                curl -H "token: 0cd52177-868d-4982-ac51-f1e6b661064a" --request GET https://api.memstash.io/values/ips >> ~/inventory.txt && 
                export ANSIBLE_HOST_KEY_CHECKING=False && ansible-playbook  -i ~/inventory.txt .circleci/ansible/roles/deploy/playbook.yml --extra-vars "TYPEORM_HOST=${TYPEORM_HOST} TYPEORM_PORT=${TYPEORM_PORT} TYPEORM_USERNAME=${TYPEORM_USERNAME} TYPEORM_PASSWORD=${TYPEORM_PASSWORD} TYPEORM_DATABASE=${TYPEORM_DATABASE}"
        - destroy-environment-linux:
            bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
            cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
            
  deploy-frontend:  
      docker: 
        - image: node
      steps:
        - checkout
        - run:
            name: export api url
            command: |
               export API=$(curl -H "token: 0cd52177-868d-4982-ac51-f1e6b661064a" --request GET https://api.memstash.io/values/ips)
        - run:
            name: deploy 
            command: cd ~/project/frontend && npm i && npm run build
        - destroy-environment-linux:
            bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
            cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
        - persist_to_workspace:
           root: ./
           paths:
              - ./frontend/node_modules  
              - ./frontend/dist
  
  copy-frontend-files-to-s3:
     docker:
       - image: amazon/aws-cli
     steps:
       - checkout
       - run:
           name: add tar
           command: yum install -y tar gzip
       - attach_workspace:
           at: ./ 
       - run: 
           name: list all files
           command: ls ~/project/frontend/
       - run: 
           name: copy files to s3
           command: aws s3 cp ~/project/frontend/dist s3://frontend${CIRCLE_WORKFLOW_ID:0:7}/ --recursive
       - destroy-environment:
           bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
           cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"    

  smoke-test:
     docker:
       - image: amazon/aws-cli
     steps: 
       - run:
           name: smoketest for backend
           command: | 
                BACKEND_IP=$(aws ec2 describe-instances \
                --query 'Reservations[*].Instances[*].PublicIpAddress' \
                --output text)
                curl "http://${BACKEND_IP}:3030/api/status"

       - run:
           name: smoketest for frontend
           command: | 
                URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
                if curl -s ${URL} | grep "Welcome"
                then
                return 1
                else
                return 0
                fi
       - destroy-environment:
           bucket_name: "frontend${CIRCLE_WORKFLOW_ID:0:7}"
           cf_stack: "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}"
#  cloudfront-update:

workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
      # - test-frontend:
      #     requires:
      #        - build-frontend
      # - test-backend:
      #     requires:
      #        - build-backend
      - scan-frontend:
          requires:
             - test-frontend
      - scan-backend:
          requires:
             - test-backend
      - configure-infrastructure
      - deploy-backend:
          requires:
             - configure-infrastructure
      - run-migrations:
          requires:
             - build-backend
      - deploy-backend-andmovecode:
          requires:
             - build-backend
      - deploy-frontend:
          requires:
             - deploy-backend-andmovecode
      - copy-frontend-files-to-s3:
          requires:
             - deploy-frontend
      - smoke-test:
          requires:
             - copy-frontend-files-to-s3
             - deploy-backend-andmovecode

