version: 2.1

### It's a good practice to keep your commands at the top of the config file. In this project, you'll need at least 2 commands:

# commands:
#   destroy-environment:
#     description: Destroy backend and frontend cloudformation stacks given a workflow ID.
#     ...

#   revert-migration:
#     description: Revert the last migration if successfully run in the current workflow.
#     ...

jobs:
  hello-world: # Delete this job when you get started
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"

  build-frontend:
    docker:
      - image: node
    steps:
      - checkout   
      - run:
          name: "compile and build"
          command: |
             cd ~/project/frontend && npm i && npm run build
      - persist_to_workspace:
          root: ./
          paths:
             - ./project/frontend/node_modules  
             
  build-backend:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: "compile and build"
          command: |
             cd ~/project/backend && npm i && npm run build


  test-frontend:
    docker:
      - image: node
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run:
          name: Run unit test
          command: |
              cd ~/project/frontend && npm test

  test-backend:
    docker:
      - image: node
    steps:
      - checkout
      - run:
          name: Run unit test
          command: |
              cd ~/project/backend && npm run test         

#  est-backend:

#  can-frontend:

#  scan-backend:

#  deploy-infrastructure:

#  configure-infrastructure:

#  run-migrations:

#  deploy-frontend:

#  deploy-backend:  

#  smoke-test:

#  cloudfront-update:

workflows:
  default:
    jobs:
      # - hello-world
      - build-frontend
      - build-backend
      - test-frontend:
          requires:
             - build-frontend
      - test-backend:
          requires:
             - build-backend
